# AUTO-GENERATED by uitk.compile from metashape_workflow.ui — do not edit.
# Edit the .ui file in Qt Designer; this file is regenerated.

__source__         = 'metashape_workflow.ui'
__source_hash__    = 'd412a1f9e62988329b958915e69a77acc33be4e2b03a9f8c75df5be056e61c1c'
__binding__        = 'PySide6'
__base_class__     = 'QMainWindow'
__form_class__     = 'QtUi'
__customwidgets__  = [('Footer', 'uitk.widgets.footer'), ('Header', 'uitk.widgets.header'), ('ComboBox', 'uitk.widgets.comboBox.ComboBox.h'), ('PushButton', 'widgets.pushbutton.h')]
__uitk_tags__      = []

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'metashape_workflow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from qtpy.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from qtpy.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from qtpy.QtWidgets import (QApplication, QComboBox, QGroupBox, QMainWindow,
    QSizePolicy, QTextBrowser, QVBoxLayout, QWidget)

from uitk.widgets.comboBox.ComboBox import ComboBox
from uitk.widgets.footer import Footer
from uitk.widgets.header import Header
from widgets.pushbutton import PushButton

class Ui_QtUi(object):
    def setupUi(self, QtUi):
        if not QtUi.objectName():
            QtUi.setObjectName(u"QtUi")
        QtUi.resize(360, 460)
        QtUi.setDockNestingEnabled(True)
        self.central_widget = QWidget(QtUi)
        self.central_widget.setObjectName(u"central_widget")
        self.central_widget.setMinimumSize(QSize(360, 0))
        self.verticalLayout_2 = QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.header = Header(self.central_widget)
        self.header.setObjectName(u"header")
        self.header.setMinimumSize(QSize(0, 19))
        self.header.setMaximumSize(QSize(16777215, 19))
        font = QFont()
        font.setBold(True)
        self.header.setFont(font)

        self.verticalLayout.addWidget(self.header)

        self.grp_process = QGroupBox(self.central_widget)
        self.grp_process.setObjectName(u"grp_process")
        self.verticalLayout_3 = QVBoxLayout(self.grp_process)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.cmb000 = ComboBox(self.grp_process)
        self.cmb000.setObjectName(u"cmb000")
        self.cmb000.setMinimumSize(QSize(0, 19))
        self.cmb000.setMaximumSize(QSize(16777215, 19))
        self.cmb000.setMaxVisibleItems(40)
        self.cmb000.setMaxCount(500)
        self.cmb000.setSizeAdjustPolicy(QComboBox.AdjustToContents)
        self.cmb000.setFrame(True)

        self.verticalLayout_3.addWidget(self.cmb000)

        self.b000 = PushButton(self.grp_process)
        self.b000.setObjectName(u"b000")
        self.b000.setMinimumSize(QSize(0, 38))
        self.b000.setMaximumSize(QSize(16777215, 38))

        self.verticalLayout_3.addWidget(self.b000)


        self.verticalLayout.addWidget(self.grp_process)

        self.txt000 = QTextBrowser(self.central_widget)
        self.txt000.setObjectName(u"txt000")
        self.txt000.setMinimumSize(QSize(0, 120))
        self.txt000.setOpenLinks(False)
        self.txt000.setOpenExternalLinks(False)

        self.verticalLayout.addWidget(self.txt000)

        self.footer = Footer(self.central_widget)
        self.footer.setObjectName(u"footer")
        self.footer.setMinimumSize(QSize(0, 19))
        self.footer.setMaximumSize(QSize(16777215, 19))

        self.verticalLayout.addWidget(self.footer)


        self.verticalLayout_2.addLayout(self.verticalLayout)

        QtUi.setCentralWidget(self.central_widget)

        self.retranslateUi(QtUi)

        QMetaObject.connectSlotsByName(QtUi)
    # setupUi

    def retranslateUi(self, QtUi):
        self.header.setText(QCoreApplication.translate("QtUi", u"METASHAPE WORKFLOW", None))
        self.grp_process.setTitle("")
#if QT_CONFIG(tooltip)
        self.cmb000.setToolTip(QCoreApplication.translate("QtUi", u"Pipeline run mode (full pipeline, align-only, or refine-only).", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.b000.setToolTip(QCoreApplication.translate("QtUi", u"Run the Metashape pipeline headless in the local metashape.exe.", None))
#endif // QT_CONFIG(tooltip)
        self.b000.setText(QCoreApplication.translate("QtUi", u"Run Workflow", None))
#if QT_CONFIG(tooltip)
        self.txt000.setToolTip(QCoreApplication.translate("QtUi", u"Workflow log. Click linked paths to open them in the file explorer.", None))
#endif // QT_CONFIG(tooltip)
        pass
    # retranslateUi

